</div>
  <footer>
    <hr>
    <a href="https://github.com/mignz/DevA2"><i class="fab fa-github"></i></a> <a href="https://github.com/mignz/DevA2/blob/master/CHANGELOG.md">Changelog</a> <a href="https://github.com/mignz/DevA2#upgrading">Upgrade</a>
  </footer>
</div>

<div class="loading">
  <i class="fas fa-spinner fa-pulse"></i>
  Please wait<br>
  <small>This may take several minutes.
</div>

<script src="/js/jquery-3.3.1.min.js"></script>
<script src="/js/popper.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/devacp.js"></script>

</body>

</html>
