<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Dev&#923; 2 - Control Panel</title>
  <meta name="author" content="Miguel Nunes">
  <link rel="stylesheet" href="/css/bootstrap.min.css">
  <link rel="stylesheet" href="/css/fontawesome/css/fontawesome-all.min.css">
  <link rel="stylesheet" href="/css/style.css">
</head>

<body>

<noscript>Javascript is required, please enable it!</noscript>

<div class="container">
  <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
      <i class="fa fa-cog"></i>
      Dev&#923; 2
    </a>
  </nav>
  <?php if (isset($error)): ?>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Woops!</h4>
    <?php if (isset($error_output) and !empty($error_output)): ?>
    <p><?php echo $error; ?></p>
    <hr>
    <p class="mb-0"><pre><?php echo $error_output; ?></pre></p>
    <?php else: ?>
    <p class="mb-0"><?php echo $error; ?></p>
    <?php endif; ?>
  </div>
  <?php endif; ?>
  <div>
