<?php require_once(__DIR__ . '/layouts/header.phtml'); ?>

<h3>Control Panel &rsaquo; Add Host</h3>

<form action="/add" method="post" class="needs-validation" novalidate>
  <div class="form-group">
    <label for="domainname">Domain Name</label>
    <div class="input-group">
      <input type="text" class="form-control" name="domainname" id="domainname" placeholder="domain" pattern="[0-9A-Za-z\-.]{2,}" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" value="<?php echo isset($post) ? $post['domainname'] : null; ?>" autofocus required>
      <div class="input-group-append">
        <span class="input-group-text">.test</span>
      </div>
      <div class="invalid-feedback">
        Must be a valid domain name. Avoid adding ".test" at the end.
      </div>
    </div>
    <small class="form-text text-muted"><b>Note:</b> Adding a new virtual host requires the domain to be in your hosts file if you haven't configured something like dnsmasq to forward all .test domains to 127.0.0.1.</small>
  </div>
  <div class="form-group">
    <label for="websiteconfig">Website Configuration</label>
    <select class="custom-select" name="websiteconfig" id="websiteconfig" required>
      <option value=""<?php if (!isset($post)): ?> selected<?php endif; ?>>Select a website configuration</option>
      <option value="html"<?php if (isset($post) and $post['websiteconfig'] == 'html'): ?> selected<?php endif; ?>>Simple HTML website with rewriting</option>
      <option value="php"<?php if (isset($post) and $post['websiteconfig'] == 'php'): ?> selected<?php endif; ?>>Typical PHP website with rewriting</option>
      <option value="phalcon"<?php if (isset($post) and $post['websiteconfig'] == 'phalcon'): ?> selected<?php endif; ?>>Phalcon</option>
      <option value="custom"<?php if (isset($post) and $post['websiteconfig'] == 'custom'): ?> selected<?php endif; ?>>Custom</option>
    </select>
    <div class="invalid-feedback">
      Choose one. "Typical PHP website with rewriting" usually works anywhere.
    </div>
  </div>
  <div class="form-group custom-config<?php if (!isset($post) or $post['websiteconfig'] != 'custom'): ?> hidden<?php endif; ?>">
    <label for="customconfig">Custom Nginx Configuration</label>
  <textarea autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" class="form-control" name="customconfig" id="customconfig" rows="12"><?php if (isset($post)): ?><?php echo $post['customconfig']; ?><?php else: ?>index index.php index.html index.htm;
location / {
    autoindex on;
    try_files $uri $uri/ /index.php?$args;
}
location ~ \.php$ {
    fastcgi_pass phpfpm;
    fastcgi_intercept_errors on;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
}<?php endif; ?></textarea>
  <small class="form-text text-muted">This configuration will be tested prior to restarting the web server. If it fails, the changes will be lost.</small>
  </div>
  <div class="form-group">
    <label for="websitepath">Website Path (Public directory)</label>
    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text">/</span>
      </div>
      <input type="text" class="form-control" name="websitepath" id="websitepath" placeholder="path" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" value="<?php echo isset($post) ? $post['websitepath'] : null; ?>">
      <div class="invalid-feedback">
        Invalid path!
      </div>
    </div>
    <small class="form-text text-muted">Path to your website public directory starting from the websites path. If the directory does not exist it will be created.</small>
  </div>
  <div class="form-group">
    <div class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" id="default" name="default">
      <label class="custom-control-label" for="default">Set as default</label>
      <i class="fas fa-question-circle" data-toggle="popover" data-content="The default virtual host is accessible through localhost. This means that you can open this website on more devices through your machine's local network IP adddress."></i>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Add</button> or <a href="/">Cancel</a>
</form>

<?php require_once(__DIR__ . '/layouts/footer.phtml'); ?>
