<?php require_once(__DIR__ . '/layouts/header.phtml'); ?>

<h3 class="float-left">Control Panel</h3>
<a href="/add" class="btn btn-dark float-right add-btn"><i class="fas fa-plus-circle"></i> Add</a>
<div class="clearfix"></div>

<div class="accordion" id="accordion">
  <div class="card">
    <div class="card-header" id="vhosts_header">
      <h5 class="mb-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#vhosts" aria-expanded="true" aria-controls="vhosts">
          Virtual Hosts
        </button>
      </h5>
    </div>
    <div id="vhosts" class="collapse show" aria-labelledby="vhosts_header" data-parent="#accordion">
      <div class="card-body">
        <table class="table table-hover">
          <thead class="thead-light">
            <tr>
              <th scope="col">Hostname</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($hosts as $file => $host): ?>
            <tr <?php if(isset($get['h']) and $get['h'] == $host['domain']): ?>class="highlighted"<?php endif; ?>>
              <th scope="row" width="200">
                <span data-toggle="tooltip" title="<?php echo $file; ?>">
                  <?php if ($host['default'] !== true and $host['domain'] == 'localhost'): ?>
                    <s><?php echo $host['domain']; ?></s>
                  <?php else: ?>
                    <?php echo $host['domain']; ?>
                  <?php endif; ?>
                </span>
              </th>
              <td>
                <a href="https://<?php echo $host['domain']; ?>" class="btn btn-primary btn-sm" data-toggle="tooltip" title="Open">
                  <i class="fas fa-globe"></i>
                </a>
                <a href="/cert/<?php echo $host['domain']; ?>" class="btn btn-primary btn-sm" data-toggle="tooltip" title="Download SSL Certificate">
                  <i class="fas fa-lock"></i>
                </a>
                <?php if ($host['domain'] == 'localhost' or $host['domain'] == 'cp.test'): ?>
                <button class="btn btn-primary btn-sm" disabled>
                  <i class="fas fa-edit"></i>
                </button>
                <?php else: ?>
                <a href="/edit/<?php echo $host['domain']; ?>" class="btn btn-primary btn-sm" data-toggle="tooltip" title="Edit">
                  <i class="fas fa-edit"></i>
                </a>
                <?php endif; ?>
                <?php if ($host['default']): ?>
                <button class="btn btn-success btn-sm" data-toggle="tooltip" title="Is Default" disabled>
                  <i class="fas fa-asterisk"></i>
                </button>
                <?php else: ?>
                <a href="/default/<?php echo $host['domain']; ?>" class="btn btn-secondary btn-sm" data-toggle="tooltip" title="Set Default">
                  <i class="fas fa-asterisk"></i>
                </a>
                <? endif; ?>
                <?php if ($host['domain'] == 'localhost' or $host['domain'] == 'cp.test' or $host['default']): ?>
                <button class="btn btn-light btn-sm" data-toggle="tooltip" title="Remove" disabled>
                  <i class="fas fa-trash"></i>
                </button>
                <?php else: ?>
                <a href="/delete/<?php echo $host['domain']; ?>" class="btn btn-danger btn-sm" data-toggle="tooltip" title="Remove (No confirmation!)">
                  <i class="fas fa-trash"></i>
                </a>
                <?php endif; ?>
              </td>
            </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="versions_header">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#versions" aria-expanded="false" aria-controls="versions">
          Versions
        </button>
      </h5>
    </div>
    <div id="versions" class="collapse" aria-labelledby="versions_header" data-parent="#accordion">
      <div class="card-body">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col"></th>
              <th scope="col">Actual Version</th>
              <th scope="col">Latest Version</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row" width="200">Dev&#923; 2</th>
              <td><span class="deva-version-actual"><?php echo $ver_deva2; ?></span> with <i class="fab fa-docker" data-toggle="tooltip" title="Docker"></i></td>
              <td class="deva-version">&hellip;</td>
            </tr>
            <tr>
              <th scope="row" width="200">Alpine</th>
              <td><?php echo $ver_alpine; ?></td>
              <td class="alpine-version"></td>
            </tr>
            <tr>
              <th scope="row" width="200">Nginx</th>
              <td><?php echo $ver_nginx; ?></td>
              <td class="nginx-version"></td>
            </tr>
            <tr>
              <th scope="row" width="200">PHP</th>
              <td><?php echo $ver_php; ?>&nbsp;&nbsp;<a href="/phpinfo" data-toggle="tooltip" title="Show phpinfo()"><i class="fab fa-php"></i></a></td>
              <td class="php-version">&hellip;</td>
            </tr>
            <tr>
              <th scope="row" width="200">MariaDB</th>
              <td><?php echo $ver_db; ?></td>
              <td class="mariadb-version"></td>
            </tr>
            <tr>
              <th scope="row" width="200">Phalcon</th>
              <td class="phalcon-version-actual"><?php echo $ver_phalcon; ?></td>
              <td class="phalcon-version">&hellip;</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="services_header">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#services" aria-expanded="false" aria-controls="services">
          Services
        </button>
      </h5>
    </div>
    <div id="services" class="collapse" aria-labelledby="services_header" data-parent="#accordion">
      <div class="card-body">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">Service</th>
              <th scope="col">Status</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row" width="200">Nginx</th>
              <td>
                <span class="badge badge-success">RUNNING</span>&nbsp;&nbsp;<small>
                  <a href="#" class="restart-service" service="nginx" data-toggle="tooltip" title="Restart Nginx"><i class="fas fa-sync-alt"></i></a>
                </small>
              </td>
            </tr>
            <tr>
              <th scope="row" width="200">PHP-FPM</th>
              <td>
                <span class="badge badge-success">RUNNING</span>&nbsp;&nbsp;<small>
                  <a href="#" class="restart-service" service="php-fpm" data-toggle="tooltip" title="Restart PHP-FPM"><i class="fas fa-sync-alt"></i></a>
                </small>
              </td>
            </tr>
            <tr>
              <th scope="row" width="200">MySQL</th>
              <td>
                <span class="badge badge-<?php echo $sql_badge; ?>"><?php echo $sql_status; ?></span>&nbsp;&nbsp;<small>
                  <a href="#" class="restart-service" service="mysql" data-toggle="tooltip" title="Restart MySQL (MariaDB)"><i class="fas fa-sync-alt"></i></a>
                </small>
              </td>
            </tr>
            <tr>
              <th scope="row" width="200">Redis</th>
              <td>
                <span class="badge badge-<?php echo $redis_badge; ?>"><?php echo $redis_status; ?></span>&nbsp;&nbsp;<small>
                  <a href="#" class="restart-service" service="redis" data-toggle="tooltip" title="Start/Restart Redis"><i class="fas fa-sync-alt"></i></a>
                </small>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="mailer_header">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#mailer" aria-expanded="false" aria-controls="mailer">
          PHP Mailer (SMTP)
        </button>
      </h5>
    </div>
    <div id="mailer" class="collapse" aria-labelledby="mailer_header" data-parent="#accordion">
      <div class="card-body">
        <form action="/smtp" method="post" class="needs-validation" novalidate>
          <div class="form-group">
            <label for="server">SMTP Server</label>
            <input name="server" type="text" class="form-control" id="server" value="<?php echo $smtp['server']; ?>" pattern="[a-zA-Z0-9\-_.]{3,}" required placeholder="mail.domain.com">
            <div class="invalid-feedback">
              You must specify an SMTP server!
            </div>
          </div>
          <div class="form-group">
            <label for="port">SMTP Server Port</label>
            <input name="port" type="number" class="form-control" id="port" value="<?php echo $smtp['port']; ?>" required placeholder="25">
            <div class="invalid-feedback">
              You must specify an SMTP server numeric port!
            </div>
          </div>
          <div class="form-group">
            <label for="user">SMTP Username</label>
            <input name="user" type="text" class="form-control" id="user" value="<?php echo $smtp['user']; ?>" pattern="[a-zA-Z0-9\-_.@]{3,}" required placeholder="address@domain.com">
            <div class="invalid-feedback">
              You must specify an SMTP username (usually an email address)!
            </div>
          </div>
          <div class="form-group">
            <label for="pass">SMTP Password</label>
            <input name="pass" type="password" class="form-control" id="pass" value="<?php echo $smtp['pass']; ?>" placeholder="Password">
            <div class="invalid-feedback">
              You must specify the SMTP password!
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Apply</button>
          <input type="button" class="btn btn-secondary" data-toggle="tooltip" title="Send a test email" onclick="testEmail()" value="Test">
        </form>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="timezone_header">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#timezone" aria-expanded="false" aria-controls="timezone">
          PHP Timezone
        </button>
      </h5>
    </div>
    <div id="timezone" class="collapse" aria-labelledby="timezone_header" data-parent="#accordion">
      <div class="card-body">
        <form action="/timezone" method="post" class="needs-validation" novalidate>
          <div class="form-group">
            <label for="timezone">Timezone</label>
            <select name="timezone" id="timezone" class="form-control" required>
              <option value="">Select a timezone</option>
              <?php foreach ($timezones as $tzk => $tz): ?>
                <option value="<?php echo $tzk; ?>"<?php if($tzk == $timezone): ?> selected<?php endif; ?>><?php echo $tz; ?></option>
              <?php endforeach; ?>
            </select>
            <div class="invalid-feedback">
              You must specify a timezone!
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Apply</button>
        </form>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="backup_header">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#backup" aria-expanded="false" aria-controls="backup">
          Backup/Restore
        </button>
      </h5>
    </div>
    <div id="backup" class="collapse" aria-labelledby="backup_header" data-parent="#accordion">
      <div class="card-body">
        <p><a href="/backup?w=1&amp;d=1&amp;v=1" class="btn btn-primary backup-link" onclick="return showLoadingScreen('This may take a while, continue?')">Create Backup</a></p>
        <p>What's included:</p>
        <p>
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input backup-sel" id="backup_w" checked>
            <label class="custom-control-label" for="backup_w">Website files</label>
          </div>
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input backup-sel" id="backup_d" checked>
            <label class="custom-control-label" for="backup_d">Databases</label>
          </div>
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input backup-sel" id="backup_v" checked>
            <label class="custom-control-label" for="backup_v">Virtual Hosts (Config)</label>
          </div>
        </p>
        <hr>
        <h3>Restore</h3>
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">Backup File</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach($files as $file): ?>
            <tr>
              <th scope="row"><?php echo basename($file); ?></th>
              <td>
                <a href="/restore/<?php echo basename($file); ?>" class="btn btn-sm btn-primary" onclick="return showLoadingScreen('This may take a while, continue?')">Restore</a>
                <a href="/deletebackup/<?php echo basename($file); ?>" class="btn btn-sm btn-danger" onclick="return showLoadingScreen('Delete this backup file?\nThis action is irreversible!')">Delete</a>
              </td>
            </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
        <small><b>Note:</b> Place your backup files in the websites directory with a valid name, for example: <i>DevA2_Backup_<?php echo date('Y-m-d_Hi'); ?>.tar.gz</i>.</small><br>
        <small><b>Warning:</b> Restoring a previous backup will replace any existing conflicting files! For the best results, make sure this is a clean installation of Dev&#923;2.</small>
      </div>
    </div>
  </div>
</div>

<?php require_once(__DIR__ . '/layouts/footer.phtml'); ?>
