<?php require_once(__DIR__ . '/layouts/header.phtml'); ?>

<h3>Upgrade Phalcon</h3>

<div class="jumbotron phalcon-upgrade">
    <i class="fa fa-cog fa-spin"></i> Running the upgrade script, this may take several minutes...<br><br><small>This message will change when the script detects that the framework has been successfully upgraded. If you suspect it is taking too long, try upgrading manually.</small>
</div>

<?php require_once(__DIR__ . '/layouts/footer.phtml'); ?>
